name: Build and Release Firmware

on:
  # For testing, we'll trigger manually
  workflow_dispatch:
  # Later, uncomment to trigger on specific tags
  # push:
  #   tags:
  #     - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y make curl tar gawk grep coreutils openssl

      - name: Build precertificate firmware
        run: |
          cd precertificate-firmware
          make

      - name: Build self-signed firmware
        run: |
          cd self-signed-firmware/automated
          make

      - name: Create Precertificate Release
        id: create_precert_release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'workflow_dispatch'
        with:
          draft: true
          tag_name: v0.0.1-precert
          files: |
            precertificate-firmware/firmware/Neato_4.2.0_102.tgz
            precertificate-firmware/firmware/Neato_4.5.3_189.tgz
            precertificate-firmware/firmware/Neato_4.6.0_72.tgz
          name: Precertificate-signed Firmware Release
          body: |
            Precertificate-signed firmware versions:
            - 4.2.0_102
            - 4.5.3_189
            - 4.6.0_72
      
      - name: Create Self-signed Release
        id: create_self_signed_release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'workflow_dispatch'
        with:
          draft: true
          tag_name: v0.0.1-self-signed
          files: |
            self-signed-firmware/automated/Neato_4.5.3_189.tgz
          name: Self-signed Firmware Release
          body: |
            Self-signed firmware version:
            - 4.5.3_189

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
